### ISSUE TITLE
IP filtering of the stoa should be checked.

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/stoa#112]
Could not access Stoa's endpoint '/block_externalized' and '/preimage_received' in the Docker Container.

**Comment by Geod24** [comment]
Duplicate of #111 ?

**Comment by MichaelKim20** [comment]
I will close this PR because the issue has already been resolved by #85.

**Comment by MichaelKim20** [comment]
I will close this PR because the issue has already been resolved by #85.
