### ISSUE TITLE
Make all path relatives to the current working directory

### ISSUE THREAD

**Issue by Geod24** [bosagora/stoa#121]
At the moment Stoa uses `appRoot` in many places. This creates issues while deploying with `docker`, as it stores the data and logs in a position relative to the binary which cannot be easily overriden.
Instead, `appRoot` shouldn't be used, and relative path should be resolved relative to the working directory.

**Comment by MichaelKim20** [comment]
The places where `appRoot` is used were all used as below.
path.resolve(appRoot.toString(), 'B')
If B is an absolute path starting with "/", the value of B is used. 
ex) /stoa/stoa/database => /stoa/stoa/database
However, without "/", the appRoot and B are combined.
ex) stoa/database   => /stoa/stoa/database

**Comment by Geod24** [comment]
`appRoot` gives the application directory.
The content of this repository is copied to `/stoa/bin/` in the docker image, so `appRoot` turns out to be `/stoa/bin/stoa/`.
In the live system, we mount `/srv/stoa` from the server to `/stoa/wd/` (working directory).
The config file is stored in `/srv/stoa/config.yaml`, and as a result is available as `/stoa/wd/config.yaml`.
So we're starting the image with `docker run <img> -- -c /stoa/wd/config.yaml`, and want `data` and `logs` to be written to `/stoa/wd/{data,logs}` so that if we stop and restart stoa, the data persists, and can be inspected from the host.

**Comment by MichaelKim20** [comment]
Nodes exist in multiple directories on multiple source files. Because the location of the current folder is different for each file, a base point is required. So it was developed based on the root of the app.
Therefore, I don't think this is a bug in the program.
I think this issue is to change the way we operate.
And I think it is good to use cwd.And I think it is good to use cwd.
The same goes for this, and I will save cwd at the program's starting point and change it to use it by referring to it.
I want the type-bug removed.

**Comment by Geod24** [comment]
I can see `appRoot` used here:
- https://github.com/bpfkorea/stoa/blob/91e6b1b66ad43c6e693fcac48acd57494812ce7e/src/modules/common/Logger.ts#L29 to set the log directory
- https://github.com/bpfkorea/stoa/blob/91e6b1b66ad43c6e693fcac48acd57494812ce7e/src/modules/common/Config.ts#L65 to read the config file
- https://github.com/bpfkorea/stoa/blob/91e6b1b66ad43c6e693fcac48acd57494812ce7e/src/modules/common/Config.ts#L100 to set the path of the database
- More places in `Config.ts` where it's used as the previous case.

*None* of those references refer to the source code of the application. They all refer to the data that is being handled.
The data handled shouldn't depend on the path of the application binary (or source code).
*All* the examples on the package's [npm.js page](https://www.npmjs.com/package/app-root-path) use `require`, because they refer to the source code, and not the data, that the application handles.

**Comment by MichaelKim20** [comment]
`npm start` runs in the folder with package.json. We need to find a way to run it on a different path first.

**Comment by MichaelKim20** [comment]
I'll look for it because it's not a normal method.

**Comment by Geod24** [comment]
We already use `--prefix` for this

**Comment by Geod24** [comment]
See https://github.com/bpfkorea/stoa/pull/119

**Comment by Geod24** [comment]
Fixed in #130
