### ISSUE TITLE
No error code returned on wrong height

### ISSUE THREAD

**Issue by Geod24** [bosagora/stoa#139]
Currently, starting a Stoa without Agora, and doing a `curl`, a.k.a:
```shell
$ curl http://127.0.0.1:4242/validators
```

I get an empty response on the query side, but can see that the request was processed:
```
[Stoa] 2020-10-23T04:15:10.214Z http GET /validators
```

Returning no data and no error code is surprising to the user, which is likely to always expect something.
While a bare `/validators` call should always succeed (currently fails because of #137), the following might not:
```
$ curl http://127.0.0.1:4242/validators?height=4242424242
```
And should definitely return an error code. This obviously apply to all endpoints.

**Comment by TrustHenry** [comment]
This is returning Status Code: `204` No Content.
Does Stoa need to return a different error status code?
Except 2xx?
