### ISSUE TITLE
Implement shell function to provide transactions details of specific address

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/stoa#212]
For web wallet development, we need an API endpoint that returns the transactions for a given PublicKey.

Example:

``` TypeScript
class Tx {
    hash : Hash	                    // The hash of the transaction
    height: bigint                  // The height of the block
    time: Date                      // The time of block created
    type: number                    // The type of transaction
    source : PublicKey              // Source address
    destination : PublicKey         // Destination address
    amount: bigint                  // Amount
    fee: bigint                     // Fee
}
```

Input parameters : page-size, page-index, and address.
The return type : Tx[]

We're going to use shell methods, for the time being, the way we handled them at https://github.com/bpfkorea/boa-sdk-ts/issues/16.

let base = new Date("2020-01-01 00:00:00");
let height = 1;
let time = new Date(base.getTime() + height x 10 x 60000);

**Comment by AndrejMitrovic** [comment]
`class Txs` I think you mean `class Tx`. This is the return value for just one transaction, correct?

**Comment by AndrejMitrovic** [comment]
How about the `type`? It can be a pay or a freeze.

**Comment by MichaelKim20** [comment]
@AndrejMitrovic: A transaction has multiple inputs.
Therefore, we do not know which input address paid the fee.
Therefore, we cannot show the fees for individual transfers, but we should show the fee for the transaction on the block explorer site.
Therefore, it would be better to remove the fee from the above class.
What do you think?

**Comment by AndrejMitrovic** [comment]
> Therefore, it would be better to remove the fee from the above class.

It would be much easier if Tx was the real Transaction with Inputs and Outputs + an additonal timestamp field. Then you would simply return all transactions which have at least one Input or Output that references that key. 

The wallet can easily calculate the fee, this saves network bandwidth which is important. Your own solution creates many `Tx` with duplicate hashes.

The wallet itself can define how to display that data.

**Comment by MichaelKim20** [comment]
I studied this issue more and reviewed the UI of the wallet.
As a result, we found that the following output was necessary.


**Data structure for the transactions history**

```TypeScript
/**
 * The interface of the transactions history element
 */
export interface ITxHistoryElement
{
    /**
     * Address, Public key
     */
    address: string;

    /**
     * Block height
     */
    height: string;

    /**
     * Transaction time
     */
    time: number;

    /**
     * Transaction hash
     */
    tx_hash: string;

    /**
     * Transaction type
     */
    type: number;

    /**
     * Amount
     */
    amount: string;

    /**
     * Block height at which the output of the transaction becomes available
     */
    unlock_height: string;

    /**
     * Time at which the output of the transaction becomes available
     */
    unlock_time: number;
}
```

**Data structure for the transaction overview**

```TypeScript
/**
 * The interface of the transaction overview
 */
export interface ITxOverview
{
    height: string;
    time: number;
    tx_hash: string;
    type: number;
    unlock_height: string;
    unlock_time: string;
    receivers: Array<ITxOverviewElement>;
    senders: Array<ITxOverviewElement>;
    fee: string;
}

/**
 * The interface of the transaction overview element
 */
export interface ITxOverviewElement
{
    address: string;
    amount: string;
}
```

**Comment by AndrejMitrovic** [comment]
@MichaelKim20 please contact RNS solutions to determine if this is appropriate enough for them.
