### ISSUE TITLE
Add block height and timestamp to endpoint /utxo/:address

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/stoa#226]
Endpoint `/utxo/:address` currently does not have a block and its time stamp.
We need to add them to make it easier for users to distinguish UTXOs.

**Comment by TrustHenry** [comment]
> Endpoint `/utxo/:address` currently does not have a block and its type stamp.

type stamp. <- What does it mean?

Block timestamp? Is that what you mean?

**Comment by TrustHenry** [comment]
https://github.com/bpfkorea/agora/issues/1406 The related issue is still in progress.

**Comment by MichaelKim20** [comment]
> [bpfkorea/agora#1406](https://github.com/bpfkorea/agora/issues/1406) The related issue is still in progress.

I want two items added to the endpoint.
One is the height of the block containing UTXO, and the other is the creation time of the block.
We can't get the creation time of the block right now.
However, it may be possible to use the method provided by the endpoint  /wallet/transactions/history/:address.

**Comment by TrustHenry** [comment]
https://github.com/bpfkorea/agora/issues/1441 I think it's related to this.

Each UTXOs may have a different block height for the containing transactions.
