### ISSUE TITLE
SPV: Implement endpoint `getMerklePath`

### ISSUE THREAD

**Issue by kchulj** [bosagora/stoa#298]
We need the Merkle path for the Merkle proof. The Merkle Path function needs to be implemented in the `export class AgoraClient`.

https://github.com/bosagora/stoa/blob/3eb9ea4ebdee022017351a2a581e0a38ff0c4ee2/src/modules/agora/AgoraClient.ts#L32

Part of [agora#239](https://github.com/bosagora/agora/issues/239)

**Comment by MichaelKim20** [comment]
When you create a test code, you can update the code below before using it.
https://github.com/bosagora/stoa/blob/534ef096aa1742749cc39d231b1fcfd20f4da494/tests/Utils.ts#L74-L221
