### ISSUE TITLE
An error occurs if the search result does not exist.

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/stoa#398]
stoa_1      | (node:25) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'constructor' of null
stoa_1      |     at Function.BigInt (/stoa/bin/node_modules/jsbi/dist/jsbi-cjs.js:1:705)
stoa_1      |     at /stoa/bin/src/modules/storage/LedgerStorage.ts:1088:47
stoa_1      |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
stoa_1      | (Use `node --trace-warnings ...` to show where the warning was created)
stoa_1      | (node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by waqarRns** [comment]
unable to reproduce this issue. could you suggest me the reproduable case?
