### ISSUE TITLE
Need to change the way the pending transaction is handled when calculating the balance

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/stoa#425]
The refunded amount of UTXO included in pending transactions must not be subtracted from the balance.
This is the issue @Kang-Simon  told me.

**Comment by MichaelKim20** [comment]
I'm going to treat the refunded amount as a locked amount.
And the balance is as follows.

new_spendable = old_spendable - send
new_frozen = old_frozen
new_locked = old_locked + receive

new_balance = new_spendable + new_frozen + new_locked 
or
new_balance = old_balance - send + receive

**Comment by TrustHenry** [comment]
I think it's good in terms of users.
