### ISSUE TITLE
/block_externalized endpoint does not need to be disclosed to the public.

### ISSUE THREAD

**Issue by TrustHenry** [bosagora/stoa#76]
Among the API lists released on the same port,
The endpoint received from Agora in the PUT method should not be opened to the public.
It can receive untrusted block data.
It must be communicated from a trusted Agora node.
The solution to this can be done by applying the request IP's WhiteList.
It can also divide Port if it has a firewall.
The best way to do this would be to apply IP WhiteList to the target Route.

**Comment by MichaelKim20** [comment]
Stoa uses port 3836 for one web server.
Does changing the port mean adding another port's web server to the Stoa?

**Comment by TrustHenry** [comment]
I can think of splitting the port, but much of it needs to be modified.
Requires a separate extension and may cause conflicts with DB access.
As discussed in IRL, I think the IP filter method that @MichaelKim20  suggested would be appropriate.
However, we need the technology to filter IP on each router in `express`.
