### ISSUE TITLE
Implement shell API server with `/push`, `/validators` and `/validators/{address}` endpoints

### ISSUE THREAD

**Issue by Geod24** [bosagora/stoa#9]
# Abstract

API to implement:
```
POST /push
GET /validators[?height=42]
GET /validator/{address}[?height=42]
```

## Push

The `/push` endpoint accepts and stores a block in a relational database. The schema of the database has to be documented (#7 ). No validation is required on the incoming data.
A tool to test this is implemented in bpfkora/agora#972

## Validators

The `height` parameter is optional. If present, it must accepts a positive integer. If absent, the most up to date state is expected.
`{address}` is the public key string of a node.

The return of `GET /validators` is an array of `ValidatorInfo` items, JSON serialized.
```json
[
    {
        "address": "GCEEEEEEE424242",
        "enrolled_at": 4242,
        "stake": "0xabcdefdeadbeef",
        "preimage": {
            "distance": 69,
            "hash": "0xdeadbeefbadf00d"
        }
    }
]
```

**Comment by TrustHenry** [comment]
I think the `stake` value here is the UTXO amount of the validator.

**Comment by Geod24** [comment]
It's the UTXO key, not amount.
